
server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/FelipeRodrigues26/microservice-repo
          search-paths: fornecedor,loja, transportador